[build]
buildCommand = "npm run build:shared && npm run build --workspace=passage-planner-frontend"

[deploy]
startCommand = "cd frontend && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
